### ISSUE TITLE
Some suggestions: conventions

### ISSUE THREAD

**Issue by Menrath** [bizDevelop/moodle-mod_bizexaminer#1]
First of all, thank you for creating the repository and sharing the source code.

I have two suggestions:
1. Rename the repository to the usual naming convention: `moodle-mod_bizexaminer`. This would make it clear that it is a Moodle plugin for bizexaminer and not a Moodle extension within bizexaminer.
3. Check whether it is compatible with your workflow to have the plugin in the root folder of the repository. This minimises the likelihood of breaking the workflows of third parties.

**Comment by gaambo** [comment]
Thanks for the suggestions @Menrath. 
We're working on both and plan to resolve it in the following days. Will keep you posted!

**Comment by gaambo** [comment]
In [v1.1.1](https://github.com/bizDevelop/moodle-mod_bizexaminer/releases/tag/v1.1.1) we restructured the public GitHub release repository to have all the plugin files in the root directory. 
Also the repository was renamed to `moodle-mod_bizexaminer` and the defaul branch to `main`. 
Each release will still have an installable plugin zip as well. 

@Menrath please test if it works with your workflow. Feel free to report back any issues or further suggestions. Thanks!

**Comment by Menrath** [comment]
Thank you for dealing with this so quickly! Our deployment workflow using git repositories with this repositories latest tag `v1.1.1` works.

Another issue will become relevant in the future: making clear with with Moodle-Core versions a certain plugin version is compatible with. The plugin repository at moodle.org makes this clear anyway, but within a git repository there are two main ways:

1. Using stable branches with the moodle-core naming convention like `MOODLE_402_STABLE` along with a table in the README.md that explains the relationship. Example: https://github.com/catalyst/moodle-auth_saml2#branches. The table is very useful if for example the MOODLE_402_STABLE branch also supports another version as well. It is often the case, that for a specific type of plugin the changes in a minor core upgrade don't affect it.
2. Using the `$plugin->supported` property in the version.php file. Example: `$plugin->supported = [402, 403]`. See https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/version.php#L35C1-L35C95. This is very useful as `$plugin->requires` only gives a lower boundary, but it is also very strict: the Moodle upgrade won't run when the supported version does not match with the core.

Along with the [Moodle-Plugin-CI](https://github.com/moodlehq/moodle-plugin-ci) and Behat as well as PHPUnit tests this are the clearest indicators for me as an instance admin to get an overview of the stability and supported versions of a plugin.

**Comment by gaambo** [comment]
We've gone with way 2, as proposed by you. 
We might look into using branch names for different supported Moodle versions in the future, when that becomse a topic (eg maybe when we soon will offer official compatibility with Moodle 4.3). 

We'll have a look at using [Moodle-Plugin-CI](https://github.com/moodlehq/moodle-plugin-ci). I've opened issue #2 for that.

Our plugin is still [awaiting review](https://tracker.moodle.org/browse/CONTRIB-9389) to be published in the official Moodle plugin repository, which then should also contain the information about supported versions.
