### ISSUE TITLE
camel case used in strings.

### ISSUE THREAD

**Issue by danmarsden** [bizDevelop/moodle-mod_bizexaminer#10]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "Exam Module";
should be:
$string['mystring'] = "Exam module";

Note: this is not a blocker for approval in the plugins db.

**Comment by gaambo** [comment]
Thanks for the feedback. We'll be working on that in our next release. 
Are there any further rules on that? I could only find [this info](https://moodledev.io/general/development/policies/codingstyle#capitals)
> Capitals should only be used when:
> - starting a sentence, or
> - starting a proper name, like Moodle.

**Comment by danmarsden** [comment]
that doc's the only one I remember - but keep in mind this isn't a blocker for approval - just a nice thing to tidy up.

**Comment by gaambo** [comment]
This was fixed in [v1.4.0](https://github.com/bizDevelop/moodle-mod_bizexaminer/releases/tag/v1.4.0).
