### ISSUE TITLE
CI pipeline for linting and testing

### ISSUE THREAD

**Issue by gaambo** [bizDevelop/moodle-mod_bizexaminer#2]
Suggested by @menrath in #1:
Use [Moodle-Plugin-CI](https://github.com/moodlehq/moodle-plugin-ci) to run linting, tests etc in a GitHub action to provide public available stability/support status.

Tracked internally in #100

**Comment by danmarsden** [comment]
this is really easy to add and would help you improve the plugin to comply a bit better with the standard guidelines too!

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by gaambo** [comment]
We're working on adding this. 
In a first step, we have replaced our local phpcs/linting scripts with `moodle-plugin-ci`. In a next step we will add it to run in our internal VCS on commits/merge requests. And the final step is to add it as GitHub action, so the status is always publicly visible for each release.

**Comment by gaambo** [comment]
We now use moodle-plugin-ci throughout local development, internal VCS and on GitHub actions. 
See [the action runs for v1.4.0](https://github.com/bizDevelop/moodle-mod_bizexaminer/actions/workflows/ci.yml)

[![Moodle Plugin CI](https://github.com/bizDevelop/moodle-mod_bizexaminer/actions/workflows/ci.yml/badge.svg)](https://github.com/bizDevelop/moodle-mod_bizexaminer/actions/workflows/ci.yml)
