### ISSUE TITLE
Test credentials button does not save the key?

### ISSUE THREAD

**Issue by mudrd8mz** [bizDevelop/moodle-mod_bizexaminer#5]
Just a minor usability issue I ran into. After pasting the API key credentials, I pressed the "Test credentials" button. It passed with OK but the credentials were not saved as I would expect.

**Comment by gaambo** [comment]
In [v1.3.0](https://github.com/bizDevelop/moodle-mod_bizexaminer/releases/tag/v1.3.0): Add a JS build task and disable the button if there are unsaved changes.
