### ISSUE TITLE
Custom namespaces at level 2

### ISSUE THREAD

**Issue by mudrd8mz** [bizDevelop/moodle-mod_bizexaminer#8]
Custom namespaces such as admin, api, callback_api, data_objects and others all should be under a `local` namespace.

https://moodledev.io/general/development/policies/codingstyle#rules-for-level2

**Comment by gaambo** [comment]
In [v1.3.0](https://github.com/bizDevelop/moodle-mod_bizexaminer/releases/tag/v1.3.0): Moved all classes which are not required to have a specific directory inside classes by a core api into the nested local namespace. check, event, output, privacy and task require that specific namespace and location according to their docs.
