### ISSUE TITLE
consider hiding "Use remote proctoring" option when no proctoring tools available

### ISSUE THREAD

**Issue by danmarsden** [bizDevelop/moodle-mod_bizexaminer#9]
it might be cleaner to hide the Use remote proctoring setting when no proctoring tools are available or display a message that states none are installed.

not  a blocker for plugins db approval

**Comment by gaambo** [comment]
Thank you for the feedback - this will be adressed/fixed in the next release.

**Comment by gaambo** [comment]
The remote proctor UI was redone in [v1.4.0](https://github.com/bizDevelop/moodle-mod_bizexaminer/releases/tag/v1.4.0) and this is now a part of the new UI.
